# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a815a51327952cf0c800b74ab50eea3ccf3ff3ebf44d5048da2124a3187212d56a75f00c2fb155fb8036906ae9230067db003e2e88b295161bdf485f587d27be

test:
  secret_key_base: 9ef4c7ac92b92e98632c936d21df8b88bf612ca3d75cdfd1d6225e3afe29b6795080ab8baf1d16cc28ad5e2dba3014461f34a48e47ff072a592d8d76476ecff9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
